node_clone_method: prepopulate
node_clone_nodes_without_confirm: false
node_clone_use_node_type_name: 0
node_clone_menu_links: false
_core:
  default_config_hash: BGI9vZocHhClqt0hrSthCN83dtL_dU2cnfzF5ebETO8
basic: null
publishing: null
omit: null
actions: null
form_build_id: form-FotTqz7q_pV4RfTHpKhlgQGn0ocXmfyJmyhTs011Moc
form_token: O_wsAyI51mtLkS3TgJ_ivTa0umLqeh5SvIpaEa7vMY0
form_id: node_clone_settings
