sitegroup: paragraphs
deploy_tasks:
  development:
    before_deploy:
      - cd $AMAZEEIO_WEBROOT && composer install
    after_deploy:
      - cd $AMAZEEIO_WEBROOT && drush -y updb --cache-clear=0
      - cd $AMAZEEIO_WEBROOT && drush -y cr
  production:
    before_deploy:
      - cd $AMAZEEIO_WEBROOT && composer install
    after_deploy:
      - cd $AMAZEEIO_WEBROOT && drush -y updb --cache-clear=0
      - cd $AMAZEEIO_WEBROOT && drush -y cr