language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.0

env:
  global:
    # Ensure composer is able to apply patches.
    - COMPOSER_EXIT_ON_PATCH_FAILURE=1
    # DRUPAL_TI Testing.
    - SIMPLETEST_DB="mysql://root:@localhost/drupal_travis_db"
    - SIMPLETEST_BASE_URL="http://localhost:8888"
    # Ignore deprecation warnings.
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true

before_install:
  # Remove xdebug. We aren't generating code coverage, and it slows down Composer.
  - phpenv config-rm xdebug.ini || true
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - phpenv config-add $TRAVIS_BUILD_DIR/travis-ci/travis.php.ini
  # Track our general build directory.
  - export DRUPAL_BUILD_ROOT="$(dirname "$TRAVIS_BUILD_DIR")"
  - export VENDOR_DIR="$(dirname "$TRAVIS_BUILD_DIR")/vendor"
  - export CUSTOM_MODULES_DIR="$(dirname "$TRAVIS_BUILD_DIR")/web/modules/custom"
  - export CUSTOM_THEMES_DIR="$(dirname "$TRAVIS_BUILD_DIR")/web/themes/tieto_admin"

install:
  - ./travis-ci/install.sh

before_script:
  - $VENDOR_DIR/bin/phpcs --config-set installed_paths $VENDOR_DIR/drupal/coder/coder_sniffer,$VENDOR_DIR/wimg/php-compatibility

script:
  - $VENDOR_DIR/bin/parallel-lint $CUSTOM_MODULES_DIR
  - $VENDOR_DIR/bin/parallel-lint $CUSTOM_THEMES_DIR
  - $VENDOR_DIR/bin/phpcs $CUSTOM_MODULES_DIR --standard=$TRAVIS_BUILD_DIR/phpcs.xml
  - $VENDOR_DIR/bin/phpcs $CUSTOM_THEMES_DIR --standard=$TRAVIS_BUILD_DIR/phpcs.xml
