language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2

env:
  global:
    # Ensure composer is able to apply patches.
    - COMPOSER_EXIT_ON_PATCH_FAILURE=1
    # DRUPAL_TI Testing.
    - SIMPLETEST_DB="mysql://root:@localhost/drupal_travis_db"
    - SIMPLETEST_BASE_URL="http://localhost:8888"
    # Ignore deprecation warnings.
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  fast_finish: true

before_install:
  # Remove xdebug. We aren't generating code coverage, and it slows down Composer.
  - phpenv config-rm xdebug.ini || true
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - phpenv config-add $TRAVIS_BUILD_DIR/travis-ci/travis.php.ini
  # Track our general build directory.
  - export VENDOR_DIR="$TRAVIS_BUILD_DIR/vendor"
  - export GLOBAL_VENDOR_DIR="${HOME}/.config/composer/vendor"
  - export PATH="${GLOBAL_VENDOR_DIR}/bin:${PATH}"
  - export CUSTOM_MODULES_DIR="$TRAVIS_BUILD_DIR/web/modules/custom"
  - export CUSTOM_THEMES_DIR="$TRAVIS_BUILD_DIR/web/themes/tieto_admin"
  - export DRUPAL_FILE_EXTENSIONS="php,module,inc,install,test,profile,theme"

install:
  - ./travis-ci/install.sh

script:
  - parallel-lint -e $DRUPAL_FILE_EXTENSIONS $CUSTOM_MODULES_DIR
  - parallel-lint -e $DRUPAL_FILE_EXTENSIONS $CUSTOM_THEMES_DIR
  - phpcs --standard=$TRAVIS_BUILD_DIR/phpcs.xml $CUSTOM_MODULES_DIR
  - phpcs --standard=$TRAVIS_BUILD_DIR/phpcs.xml $CUSTOM_THEMES_DIR

notifications:
  email:
    on_success: never
    on_failure: change
