name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2016-09-13
version: '8.2.0-rc1+5-dev'
core: '8.x'
project: 'drupal'
datestamp: 1473771063
