buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_google_plus\"></a>\r\n<a class=\"a2a_button_linkedin\"></a>"
additional_css: '.a2a_svg { border-radius: 50% !important; }'
additional_js: 'a2a_config.icon_color = "#aaaaaa";'
universal_button: none
custom_universal_button: ''
universal_button_placement: after
no_3p: false
_core:
  default_config_hash: 8aJF-FDdnrk-N2gLGWFQcLZIpuJZA0BE9NtgXTVJfVk
