module:
  abjs: 0
  abtestui: 0
  addtoany: 0
  aggregated_leaflet_map: 0
  allowed_formats: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  campaign_pages_tour: 0
  captcha: 0
  chart_boxes: 0
  ckeditor: 0
  classy_paragraphs: 0
  cloudfront_purger: 0
  config: 0
  config_readonly: 0
  content_entity_language_switcher: 0
  content_translation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facebook_pixel: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filefield_sources_jsonapi: 0
  filter: 0
  geocoder: 0
  geocoder_autocomplete: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  google_analytics: 0
  image: 0
  imageapi_optimize: 0
  imagemagick: 0
  inline_entity_form: 0
  lang_dropdown: 0
  language: 0
  layout_discovery: 0
  leaflet: 0
  leaflet_views: 0
  link: 0
  linkedin_autofill: 0
  machine_name: 0
  marketo_form: 0
  marketo_poll: 0
  maxlength: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  node_clone: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  parade: 0
  parade_conditional_field: 0
  parade_demo: 0
  paragraphs_type_permissions: 0
  path: 0
  public_preview: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_queuer_url: 0
  purge_tokens: 0
  purge_ui: 0
  rdf: 0
  redirect: 0
  savings_calculator: 0
  scheduled_updates: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twitter_feed_parade_type: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  view_mode_selector: 0
  view_unpublished: 0
  views_ui: 0
  campaign_pages: 1
  filefield_sources: 1
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  tieto_admin: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
profile: standard
