entity_types:
  domain_path: '0'
  gdpr_task: '0'
  node: '1'
  redirect: '0'
  scheduled_update: '0'
  shortcut: '0'
  taxonomy_term: '0'
  user: '0'
  menu_link_content: '0'
_core:
  default_config_hash: SAPiGM7aE7vhiZFjsmpbIB79736aEyeurhNji9T2oZM
