links:
  en:
    privacy_policy: 'https://www.tieto.com/privacy-notice'
    terms_of_use: ''
    about_us: 'https://www.tieto.com/about-us'
    impressum: ''
  de:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  fr:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  sv:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  fi:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  ru:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  hi:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  zh-hans:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  nb:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
  da:
    privacy_policy: ''
    terms_of_use: ''
    about_us: ''
    impressum: ''
